[package]
name = "beam"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/mod.rs"

[[bin]]
name = "beam"
path = "src/main.rs"

[dependencies]
regex = "1.10"
bimap = "0.6.3"
once_cell = "1.17.1"
clap = { version = "4.5", features = ["derive"] }
anstream = "0.6"
anstyle = "1.0"
rand = "0.8"
